name: Continue Deployment
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: build/.vuepress/dist/
