name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:

  continuous-deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14.17.0"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: "ftp://${{ secrets.FTP_HOST }}/webroot/ROOT/panduan/"
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/